version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: cerana
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    command: flask run --host=0.0.0.0
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
      DATABASE_URL: postgresql://postgres:postgres@db:5432/cerana
    ports:
      - "5001:5000"
    depends_on:
      - db
volumes:
  pgdata: