"""add company_name funding_stage title to founder_profile

Revision ID: 0eb24de16646
Revises: b0b60e119460
Create Date: 2025-06-28 19:20:14.051430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb24de16646'
down_revision: Union[str, None] = 'b0b60e119460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('founder_profiles', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('founder_profiles', sa.Column('funding_stage', sa.String(length=64), nullable=True))
    op.add_column('founder_profiles', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('founder_profiles', 'title')
    op.drop_column('founder_profiles', 'funding_stage')
    op.drop_column('founder_profiles', 'company_name')
    # ### end Alembic commands ###
