"""Initial DB schema

Revision ID: 45287dd41127
Revises: 
Create Date: 2025-06-28 14:53:47.486881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45287dd41127'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('founder_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('background', sa.String(length=64), nullable=False),
    sa.Column('experience_level', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('focus_areas', sa.ARRAY(sa.String(length=128)), nullable=False),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investor_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('firm_name', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('stage_focus', sa.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('sector_preferences', sa.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('geographic_focus', sa.String(length=255), nullable=False),
    sa.Column('check_size_range', sa.String(length=64), nullable=False),
    sa.Column('investment_style', sa.String(length=64), nullable=False),
    sa.Column('deal_flow_preference', sa.String(length=255), nullable=True),
    sa.Column('due_diligence_style', sa.String(length=255), nullable=True),
    sa.Column('value_add_areas', sa.ARRAY(sa.String(length=128)), nullable=True),
    sa.Column('investments_per_year', sa.Integer(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('accredited', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investor_profiles')
    op.drop_table('founder_profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
