"""add_hiring_platform_tables

Revision ID: 60a8d70b0b92
Revises: 89d80b3cf4a8
Create Date: 2025-07-09 16:32:23.635453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60a8d70b0b92'
down_revision: Union[str, None] = '89d80b3cf4a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('work_auth_status', sa.String(length=32), nullable=False),
    sa.Column('availability', sa.String(length=32), nullable=False),
    sa.Column('employment_status', sa.String(length=32), nullable=False),
    sa.Column('salary_expectations', sa.JSON(), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String(length=128)), nullable=False),
    sa.Column('experience_level', sa.String(length=32), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('portfolio_url', sa.String(length=255), nullable=True),
    sa.Column('certifications', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('education',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('field_of_study', sa.String(length=255), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_postings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('founder_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('required_skills', sa.ARRAY(sa.String(length=128)), nullable=False),
    sa.Column('preferred_skills', sa.ARRAY(sa.String(length=128)), nullable=True),
    sa.Column('experience_level', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('is_remote', sa.Boolean(), nullable=True),
    sa.Column('salary_range', sa.JSON(), nullable=False),
    sa.Column('equity', sa.JSON(), nullable=True),
    sa.Column('employment_type', sa.String(length=32), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('team', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['founder_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_searches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('founder_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('search_criteria', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['founder_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_experience',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('role_description', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('skills', sa.ARRAY(sa.String(length=128)), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_experience')
    op.drop_table('saved_searches')
    op.drop_table('job_postings')
    op.drop_table('education')
    op.drop_table('candidate_profiles')
    # ### end Alembic commands ###
