"""add_pipeline_deals_table

Revision ID: 89d80b3cf4a8
Revises: 0eb24de16646
Create Date: 2025-07-09 15:27:37.014157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89d80b3cf4a8'
down_revision: Union[str, None] = '0eb24de16646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_deals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investor_id', sa.String(length=36), nullable=False),
    sa.Column('founder_id', sa.String(length=36), nullable=False),
    sa.Column('founder_name', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('next_action', sa.String(length=255), nullable=True),
    sa.Column('next_action_due', sa.DateTime(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('key_metrics', sa.JSON(), nullable=True),
    sa.Column('risk_flags', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('opportunities', sa.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('notes', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['founder_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['investor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_deals')
    # ### end Alembic commands ###
