"""add_hiring_platform_tables

Revision ID: ff56ce2ae99d
Revises: 60a8d70b0b92
Create Date: 2025-07-09 16:45:16.778649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff56ce2ae99d'
down_revision: Union[str, None] = '60a8d70b0b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
